/* Generated by Yosys 0.54+29 (git sha1 67583fee4, g++ 9.5.0 -fPIC -O3) */

module TopModule(clk, j, k, reset, out);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  input clk;
  wire clk;
  input j;
  wire j;
  input k;
  wire k;
  output out;
  wire out;
  input reset;
  wire reset;
  INV_X1 _4_ (
    .A(j),
    .ZN(_1_)
  );
  MUX2_X1 _5_ (
    .A(_1_),
    .B(k),
    .S(out),
    .Z(_2_)
  );
  NOR2_X2 _6_ (
    .A1(reset),
    .A2(_2_),
    .ZN(_0_)
  );
  DFF_X1 _7_ (
    .CK(clk),
    .D(_0_),
    .Q(out),
    .QN(_3_)
  );
endmodule
