from revolution.auto_bd.netlist_hash import canonical_netlist_hash, motif_signature_hash


def test_canonical_netlist_hash_ignores_comments_instance_names_and_order():
    netlist_a = """
    // generated by yosys
    module top(input a, input b, output y);
      NAND2_X1 u0 (.A(a), .B(b), .ZN(n1));
      INV_X1 u1 (.A(n1), .ZN(y));
    endmodule
    """
    netlist_b = """
    module top(input a,input b,output y);
      /* instance names differ */
      INV_X1 renamed_2 (.ZN(y), .A(n1));
      NAND2_X1 renamed_1 (.B(b), .ZN(n1), .A(a));
    endmodule
    """

    assert canonical_netlist_hash(netlist_a) == canonical_netlist_hash(netlist_b)


def test_canonical_netlist_hash_tracks_connection_changes():
    original = "NAND2_X1 u0 (.A(a), .B(b), .ZN(y));"
    changed = "NAND2_X1 u0 (.A(a), .B(c), .ZN(y));"

    assert canonical_netlist_hash(original) != canonical_netlist_hash(changed)


def test_motif_signature_hash_ignores_net_names_but_tracks_cell_counts():
    original = "NAND2_X1 u0 (.A(a), .B(b), .ZN(y));"
    renamed = "NAND2_X1 u9 (.A(x), .B(z), .ZN(out));"
    extra_cell = """
    NAND2_X1 u0 (.A(a), .B(b), .ZN(n1));
    INV_X1 u1 (.A(n1), .ZN(y));
    """

    assert motif_signature_hash(original) == motif_signature_hash(renamed)
    assert motif_signature_hash(original) != motif_signature_hash(extra_cell)

