/* Generated by Yosys 0.54+29 (git sha1 67583fee4, g++ 9.5.0 -fPIC -O3) */

module freq_diveven(clk, rst_n, clk_div);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  input clk;
  wire clk;
  output clk_div;
  wire clk_div;
  wire \cnt[0] ;
  wire \cnt[1] ;
  wire \cnt[2] ;
  wire \cnt[3] ;
  input rst_n;
  wire rst_n;
  INV_X1 _21_ (
    .A(\cnt[0] ),
    .ZN(_00_)
  );
  NOR2_X4 _22_ (
    .A1(\cnt[3] ),
    .A2(\cnt[2] ),
    .ZN(_09_)
  );
  OR3_X4 _23_ (
    .A1(_00_),
    .A2(\cnt[1] ),
    .A3(_09_),
    .ZN(_10_)
  );
  INV_X1 _24_ (
    .A(\cnt[1] ),
    .ZN(_11_)
  );
  OAI21_X1 _25_ (
    .A(_10_),
    .B1(_11_),
    .B2(\cnt[0] ),
    .ZN(_01_)
  );
  NAND3_X2 _26_ (
    .A1(\cnt[0] ),
    .A2(_11_),
    .A3(_09_),
    .ZN(_12_)
  );
  AND2_X1 _27_ (
    .A1(_07_),
    .A2(_12_),
    .ZN(_02_)
  );
  INV_X1 _28_ (
    .A(\cnt[3] ),
    .ZN(_13_)
  );
  OR2_X1 _29_ (
    .A1(_13_),
    .A2(_06_),
    .ZN(_14_)
  );
  NAND2_X1 _30_ (
    .A1(_13_),
    .A2(_06_),
    .ZN(_15_)
  );
  NOR3_X1 _31_ (
    .A1(_00_),
    .A2(\cnt[1] ),
    .A3(\cnt[2] ),
    .ZN(_16_)
  );
  OAI21_X1 _32_ (
    .A(_14_),
    .B1(_15_),
    .B2(_16_),
    .ZN(_03_)
  );
  NOR2_X1 _33_ (
    .A1(_00_),
    .A2(_11_),
    .ZN(_05_)
  );
  MUX2_X1 _34_ (
    .A(_04_),
    .B(clk_div),
    .S(_12_),
    .Z(_08_)
  );
  HA_X1 _35_ (
    .A(\cnt[2] ),
    .B(_05_),
    .CO(_06_),
    .S(_07_)
  );
  DFFR_X1 _36_ (
    .CK(clk),
    .D(_08_),
    .Q(clk_div),
    .QN(_04_),
    .RN(rst_n)
  );
  DFFR_X1 _37_ (
    .CK(clk),
    .D(_00_),
    .Q(\cnt[0] ),
    .QN(_18_),
    .RN(rst_n)
  );
  DFFR_X1 _38_ (
    .CK(clk),
    .D(_01_),
    .Q(\cnt[1] ),
    .QN(_19_),
    .RN(rst_n)
  );
  DFFR_X1 _39_ (
    .CK(clk),
    .D(_02_),
    .Q(\cnt[2] ),
    .QN(_20_),
    .RN(rst_n)
  );
  DFFR_X1 _40_ (
    .CK(clk),
    .D(_03_),
    .Q(\cnt[3] ),
    .QN(_17_),
    .RN(rst_n)
  );
endmodule
