#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/../env.sh"

uv run python scripts/run_backend.py \
  --backend revolution \
  --benchmarks RTLLM \
  --problems "${RTLLM_PROBLEMS[@]}" \
  --api_backend vllm \
  --vllm_host "$VLLM_HOST" \
  --vllm_port "$VLLM_PORT" \
  --vllm_min_model_len 128000 \
  --model_name "$MODEL_NAME" \
  --max_tokens "$MAX_TOKENS" \
  --diff_max_tokens "$DIFF_MAX_TOKENS" \
  --population_size "$BUDGET_POPULATION" \
  --num_generations "$BUDGET_GENERATIONS" \
  --evaluation_mode strict_ablation \
  --temperature 1.0 \
  --top_p 1.0 \
  --total_worker_slots "$COMMON_TOTAL_WORKER_SLOTS" \
  --max_active_problems "$COMMON_MAX_ACTIVE_PROBLEMS" \
  --max_workers_per_problem "$COMMON_MAX_WORKERS_PER_PROBLEM" \
  --seed "$SEED" \
  --no-backend_subdir \
  --search_mode revolution_qd \
  --qd_archive_type grid_quantile \
  --qd_grid_quantile_warmup_successes 4 \
  --qd_archive_activation_generation 3 \
  --qd_fill_target_fraction 0.10 \
  --qd_improve_backfill_fraction 0.05 \
  --qd_cell_mode elite_pareto_slot \
  --qd_max_elites_per_cell 2 \
  --qd_objectives ppa \
  --qd_champion_lane_fraction 0.90 \
  --qd_parent_selection nsga2_global_rank \
  --qd_two_parent_probability 0.0 \
  --qd_two_parent_gate none \
  --qd_operator_kind single_thought_operator \
  --qd_operator_one_parent_fraction 1.0 \
  --qd_operator_archive_context_size 4 \
  --qd_operator_fail_feedback_chars 0 \
  --representation_kind code_individual \
  --repair_kind none \
  --repair_max_attempts_per_sample 0 \
  --repair_max_attempts_per_thought 0 \
  --repair_evidence stage_scoped_logs \
  --qd_descriptor_profile source_aligned_masterrtl_structural_mix_3d \
  --save_path "$(method_save_path masterrtl_delayed_archive_activation_8x5)"
