/* Generated by Yosys 0.54+29 (git sha1 67583fee4, g++ 9.5.0 -fPIC -O3) */

module multi_pipe_4bit(clk, rst_n, mul_a, mul_b, mul_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  input clk;
  wire clk;
  input [3:0] mul_a;
  wire [3:0] mul_a;
  input [3:0] mul_b;
  wire [3:0] mul_b;
  output [7:0] mul_out;
  wire [7:0] mul_out;
  wire \pp[0][0] ;
  input rst_n;
  wire rst_n;
  wire \sum_stage1[0] ;
  wire \sum_stage1[1] ;
  wire \sum_stage1[2] ;
  wire \sum_stage1[3] ;
  wire \sum_stage1[4] ;
  wire \sum_stage1[5] ;
  wire \sum_stage2[0] ;
  wire \sum_stage2[1] ;
  wire \sum_stage2[2] ;
  wire \sum_stage2[3] ;
  wire \sum_stage2[4] ;
  wire \sum_stage2[5] ;
  wire \sum_stage2[6] ;
  wire \sum_stage2[7] ;
  AND2_X1 _078_ (
    .A1(mul_b[0]),
    .A2(mul_a[0]),
    .ZN(\pp[0][0] )
  );
  AND2_X1 _079_ (
    .A1(mul_b[1]),
    .A2(mul_a[2]),
    .ZN(_003_)
  );
  AND2_X1 _080_ (
    .A1(mul_b[0]),
    .A2(mul_a[3]),
    .ZN(_004_)
  );
  NAND2_X2 _081_ (
    .A1(mul_b[1]),
    .A2(mul_a[3]),
    .ZN(_043_)
  );
  XNOR2_X2 _082_ (
    .A(_005_),
    .B(_043_),
    .ZN(_042_)
  );
  AOI21_X1 _083_ (
    .A(_024_),
    .B1(_025_),
    .B2(_002_),
    .ZN(_044_)
  );
  NOR2_X1 _084_ (
    .A1(_043_),
    .A2(_044_),
    .ZN(_041_)
  );
  NAND2_X1 _085_ (
    .A1(mul_a[1]),
    .A2(mul_b[3]),
    .ZN(_006_)
  );
  NAND2_X1 _086_ (
    .A1(mul_a[2]),
    .A2(mul_b[3]),
    .ZN(_017_)
  );
  XNOR2_X1 _087_ (
    .A(_015_),
    .B(_037_),
    .ZN(_040_)
  );
  AND2_X1 _088_ (
    .A1(mul_a[3]),
    .A2(mul_b[3]),
    .ZN(_022_)
  );
  NAND2_X1 _089_ (
    .A1(mul_a[0]),
    .A2(mul_b[3]),
    .ZN(_010_)
  );
  INV_X1 _090_ (
    .A(_033_),
    .ZN(_014_)
  );
  NAND2_X1 _091_ (
    .A1(mul_a[2]),
    .A2(mul_b[2]),
    .ZN(_007_)
  );
  NAND2_X1 _092_ (
    .A1(mul_a[1]),
    .A2(mul_b[2]),
    .ZN(_011_)
  );
  NAND2_X1 _093_ (
    .A1(mul_a[3]),
    .A2(mul_b[2]),
    .ZN(_018_)
  );
  NAND3_X1 _094_ (
    .A1(_033_),
    .A2(_032_),
    .A3(_037_),
    .ZN(_045_)
  );
  AOI21_X1 _095_ (
    .A(_036_),
    .B1(_031_),
    .B2(_037_),
    .ZN(_046_)
  );
  NAND2_X1 _096_ (
    .A1(_045_),
    .A2(_046_),
    .ZN(_023_)
  );
  INV_X1 _097_ (
    .A(_013_),
    .ZN(_038_)
  );
  INV_X1 _098_ (
    .A(_016_),
    .ZN(_039_)
  );
  AND2_X1 _099_ (
    .A1(mul_b[1]),
    .A2(mul_a[1]),
    .ZN(_000_)
  );
  AND2_X1 _100_ (
    .A1(mul_a[0]),
    .A2(mul_b[1]),
    .ZN(_026_)
  );
  AND2_X1 _101_ (
    .A1(mul_a[0]),
    .A2(mul_b[2]),
    .ZN(_028_)
  );
  INV_X1 _102_ (
    .A(_009_),
    .ZN(_029_)
  );
  INV_X1 _103_ (
    .A(_008_),
    .ZN(_034_)
  );
  INV_X1 _104_ (
    .A(_019_),
    .ZN(_021_)
  );
  AND2_X1 _105_ (
    .A1(mul_b[0]),
    .A2(mul_a[2]),
    .ZN(_001_)
  );
  AND2_X1 _106_ (
    .A1(mul_b[0]),
    .A2(mul_a[1]),
    .ZN(_027_)
  );
  INV_X1 _107_ (
    .A(_012_),
    .ZN(_030_)
  );
  INV_X1 _108_ (
    .A(_020_),
    .ZN(_035_)
  );
  FA_X1 _109_ (
    .A(_000_),
    .B(_066_),
    .CI(_001_),
    .CO(_002_),
    .S(_067_)
  );
  FA_X1 _110_ (
    .A(_003_),
    .B(_004_),
    .CI(_002_),
    .CO(_005_),
    .S(_068_)
  );
  FA_X1 _111_ (
    .A(_069_),
    .B(_006_),
    .CI(_007_),
    .CO(_008_),
    .S(_009_)
  );
  FA_X1 _112_ (
    .A(_070_),
    .B(_010_),
    .CI(_011_),
    .CO(_012_),
    .S(_013_)
  );
  FA_X1 _113_ (
    .A(_009_),
    .B(_014_),
    .CI(_012_),
    .CO(_015_),
    .S(_016_)
  );
  FA_X1 _114_ (
    .A(_071_),
    .B(_017_),
    .CI(_018_),
    .CO(_019_),
    .S(_020_)
  );
  FA_X1 _115_ (
    .A(_021_),
    .B(_022_),
    .CI(_023_),
    .CO(_072_),
    .S(_073_)
  );
  HA_X1 _116_ (
    .A(_003_),
    .B(_004_),
    .CO(_024_),
    .S(_025_)
  );
  HA_X1 _117_ (
    .A(_026_),
    .B(_027_),
    .CO(_066_),
    .S(_074_)
  );
  HA_X1 _118_ (
    .A(\sum_stage1[2] ),
    .B(_028_),
    .CO(_075_),
    .S(_076_)
  );
  HA_X1 _119_ (
    .A(_029_),
    .B(_030_),
    .CO(_031_),
    .S(_032_)
  );
  HA_X1 _120_ (
    .A(_034_),
    .B(_035_),
    .CO(_036_),
    .S(_037_)
  );
  HA_X1 _121_ (
    .A(_038_),
    .B(_075_),
    .CO(_033_),
    .S(_077_)
  );
  DFFR_X1 _122_ (
    .CK(clk),
    .D(\pp[0][0] ),
    .Q(\sum_stage1[0] ),
    .QN(_048_),
    .RN(rst_n)
  );
  DFFR_X1 _123_ (
    .CK(clk),
    .D(_074_),
    .Q(\sum_stage1[1] ),
    .QN(_049_),
    .RN(rst_n)
  );
  DFFR_X1 _124_ (
    .CK(clk),
    .D(_067_),
    .Q(\sum_stage1[2] ),
    .QN(_050_),
    .RN(rst_n)
  );
  DFFR_X1 _125_ (
    .CK(clk),
    .D(_068_),
    .Q(\sum_stage1[3] ),
    .QN(_070_),
    .RN(rst_n)
  );
  DFFR_X1 _126_ (
    .CK(clk),
    .D(_042_),
    .Q(\sum_stage1[4] ),
    .QN(_069_),
    .RN(rst_n)
  );
  DFFR_X1 _127_ (
    .CK(clk),
    .D(_041_),
    .Q(\sum_stage1[5] ),
    .QN(_071_),
    .RN(rst_n)
  );
  DFFR_X1 _128_ (
    .CK(clk),
    .D(\sum_stage2[0] ),
    .Q(mul_out[0]),
    .QN(_051_),
    .RN(rst_n)
  );
  DFFR_X1 _129_ (
    .CK(clk),
    .D(\sum_stage2[1] ),
    .Q(mul_out[1]),
    .QN(_052_),
    .RN(rst_n)
  );
  DFFR_X1 _130_ (
    .CK(clk),
    .D(\sum_stage2[2] ),
    .Q(mul_out[2]),
    .QN(_053_),
    .RN(rst_n)
  );
  DFFR_X1 _131_ (
    .CK(clk),
    .D(\sum_stage2[3] ),
    .Q(mul_out[3]),
    .QN(_054_),
    .RN(rst_n)
  );
  DFFR_X1 _132_ (
    .CK(clk),
    .D(\sum_stage2[4] ),
    .Q(mul_out[4]),
    .QN(_055_),
    .RN(rst_n)
  );
  DFFR_X1 _133_ (
    .CK(clk),
    .D(\sum_stage2[5] ),
    .Q(mul_out[5]),
    .QN(_056_),
    .RN(rst_n)
  );
  DFFR_X1 _134_ (
    .CK(clk),
    .D(\sum_stage2[6] ),
    .Q(mul_out[6]),
    .QN(_057_),
    .RN(rst_n)
  );
  DFFR_X1 _135_ (
    .CK(clk),
    .D(\sum_stage2[7] ),
    .Q(mul_out[7]),
    .QN(_058_),
    .RN(rst_n)
  );
  DFFR_X1 _136_ (
    .CK(clk),
    .D(\sum_stage1[0] ),
    .Q(\sum_stage2[0] ),
    .QN(_059_),
    .RN(rst_n)
  );
  DFFR_X1 _137_ (
    .CK(clk),
    .D(\sum_stage1[1] ),
    .Q(\sum_stage2[1] ),
    .QN(_060_),
    .RN(rst_n)
  );
  DFFR_X1 _138_ (
    .CK(clk),
    .D(_076_),
    .Q(\sum_stage2[2] ),
    .QN(_061_),
    .RN(rst_n)
  );
  DFFR_X1 _139_ (
    .CK(clk),
    .D(_077_),
    .Q(\sum_stage2[3] ),
    .QN(_062_),
    .RN(rst_n)
  );
  DFFR_X1 _140_ (
    .CK(clk),
    .D(_039_),
    .Q(\sum_stage2[4] ),
    .QN(_063_),
    .RN(rst_n)
  );
  DFFR_X1 _141_ (
    .CK(clk),
    .D(_040_),
    .Q(\sum_stage2[5] ),
    .QN(_064_),
    .RN(rst_n)
  );
  DFFR_X1 _142_ (
    .CK(clk),
    .D(_073_),
    .Q(\sum_stage2[6] ),
    .QN(_065_),
    .RN(rst_n)
  );
  DFFR_X1 _143_ (
    .CK(clk),
    .D(_072_),
    .Q(\sum_stage2[7] ),
    .QN(_047_),
    .RN(rst_n)
  );
endmodule
