/* Generated by Yosys 0.54+29 (git sha1 67583fee4, g++ 9.5.0 -fPIC -O3) */

module cla_4bit(A, B, Cin, S, Pg, Gg, Cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  input [3:0] A;
  wire [3:0] A;
  input [3:0] B;
  wire [3:0] B;
  input Cin;
  wire Cin;
  output Cout;
  wire Cout;
  output Gg;
  wire Gg;
  output Pg;
  wire Pg;
  output [3:0] S;
  wire [3:0] S;
  BUF_X4 _26_ (
    .A(_12_),
    .Z(_13_)
  );
  BUF_X4 _27_ (
    .A(_08_),
    .Z(_14_)
  );
  AND4_X1 _28_ (
    .A1(_13_),
    .A2(_06_),
    .A3(_14_),
    .A4(_10_),
    .ZN(Pg)
  );
  INV_X1 _29_ (
    .A(_10_),
    .ZN(_15_)
  );
  NAND3_X1 _30_ (
    .A1(_13_),
    .A2(_05_),
    .A3(_14_),
    .ZN(_16_)
  );
  AOI21_X4 _31_ (
    .A(_11_),
    .B1(_07_),
    .B2(_13_),
    .ZN(_17_)
  );
  AOI21_X1 _32_ (
    .A(_15_),
    .B1(_16_),
    .B2(_17_),
    .ZN(_18_)
  );
  OR2_X1 _33_ (
    .A1(_09_),
    .A2(_18_),
    .ZN(Gg)
  );
  INV_X1 _34_ (
    .A(_09_),
    .ZN(_19_)
  );
  NAND4_X2 _35_ (
    .A1(_13_),
    .A2(Cin),
    .A3(_06_),
    .A4(_14_),
    .ZN(_20_)
  );
  AND3_X4 _36_ (
    .A1(_16_),
    .A2(_17_),
    .A3(_20_),
    .ZN(_21_)
  );
  OAI21_X2 _37_ (
    .A(_19_),
    .B1(_15_),
    .B2(_21_),
    .ZN(Cout)
  );
  XNOR2_X1 _38_ (
    .A(_03_),
    .B(_14_),
    .ZN(S[1])
  );
  INV_X1 _39_ (
    .A(_07_),
    .ZN(_22_)
  );
  AOI21_X1 _40_ (
    .A(_05_),
    .B1(Cin),
    .B2(_06_),
    .ZN(_23_)
  );
  INV_X1 _41_ (
    .A(_14_),
    .ZN(_24_)
  );
  OAI21_X1 _42_ (
    .A(_22_),
    .B1(_23_),
    .B2(_24_),
    .ZN(_25_)
  );
  XOR2_X1 _43_ (
    .A(_13_),
    .B(_25_),
    .Z(S[2])
  );
  XNOR2_X2 _44_ (
    .A(_10_),
    .B(_21_),
    .ZN(S[3])
  );
  INV_X1 _45_ (
    .A(A[0]),
    .ZN(_00_)
  );
  INV_X1 _46_ (
    .A(B[0]),
    .ZN(_01_)
  );
  INV_X1 _47_ (
    .A(Cin),
    .ZN(_02_)
  );
  INV_X1 _48_ (
    .A(_04_),
    .ZN(S[0])
  );
  FA_X1 _49_ (
    .A(_00_),
    .B(_01_),
    .CI(_02_),
    .CO(_03_),
    .S(_04_)
  );
  HA_X1 _50_ (
    .A(A[0]),
    .B(B[0]),
    .CO(_05_),
    .S(_06_)
  );
  HA_X1 _51_ (
    .A(A[1]),
    .B(B[1]),
    .CO(_07_),
    .S(_08_)
  );
  HA_X1 _52_ (
    .A(A[3]),
    .B(B[3]),
    .CO(_09_),
    .S(_10_)
  );
  HA_X1 _53_ (
    .A(A[2]),
    .B(B[2]),
    .CO(_11_),
    .S(_12_)
  );
endmodule
