/* Generated by Yosys 0.54+29 (git sha1 67583fee4, g++ 9.5.0 -fPIC -O3) */

module TopModule(clk, j, k, areset, out);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  input areset;
  wire areset;
  input clk;
  wire clk;
  input j;
  wire j;
  input k;
  wire k;
  output out;
  wire out;
  INV_X1 _4_ (
    .A(k),
    .ZN(_2_)
  );
  MUX2_X1 _5_ (
    .A(j),
    .B(_2_),
    .S(out),
    .Z(_0_)
  );
  INV_X1 _6_ (
    .A(areset),
    .ZN(_1_)
  );
  DFFR_X1 _7_ (
    .CK(clk),
    .D(_0_),
    .Q(out),
    .QN(_3_),
    .RN(_1_)
  );
endmodule
