"""Build drop-in LaTeX result tables for the journal manuscript from the run
stats. Mechanical artifact generation (not prose): reads the official
report_journal_statistics JSONs + the RealBench/CVDP grading artifacts and emits
booktabs tables to docs/journal_features/manuscript_artifacts/tables.tex. Numbers
are sourced from the cited run directories; re-run to regenerate after any run.

Usage: python scripts/build_manuscript_tables.py
"""

import json
from pathlib import Path

OUT = Path("docs/journal_features/manuscript_artifacts/tables.tex")


def bq(path: str) -> dict | None:
    """Read best_quality stats (mean/CI/p/win-rate) from a stats JSON, or None."""
    p = Path(path) / "statistical_tests.json"
    if not p.is_file():
        return None
    m = json.loads(p.read_text()).get("metrics", {}).get("best_quality", {})
    return {
        "mean": m.get("mean_delta"),
        "lo": m.get("bootstrap_ci_low"),
        "hi": m.get("bootstrap_ci_high"),
        "p": m.get("sign_test_p"),
        "win": m.get("win_rate_non_tied"),
    } if m else None


def fmt(d: dict | None) -> str:
    if not d or d["mean"] is None:
        return "-- & -- & --"
    p = d["p"]
    ps = "<1e-4" if p is not None and p < 1e-4 else (f"{p:.2f}" if p is not None else "--")
    return f"${d['mean']:+.3f}$ & $[{d['lo']:+.3f}, {d['hi']:+.3f}]$ & {ps}"


M = "exp/ablation_matrix/stats"
S = "exp/fast_iter"
rows = {
    "F1": ("qd\\_target $-$ classic (radical QD vs classic)", bq(f"{M}/final_5seed_F1_qt_vs_classic")),
    "F2": ("qd\\_target $-$ qd\\_six\\_operators (operator ablation, within QD)", bq(f"{M}/final_5seed_F2_qt_vs_six")),
    "F23v2": ("smooth-QD V2 $-$ classic (NSGA-II; \\emph{our method})", bq(f"{S}/smooth_qd_nsga2/stats_5seed_vs_classic")),
    "F23v1": ("smooth-QD V1 $-$ classic (no NSGA-II; ablation)", bq(f"{S}/smooth_qd_code_individual/stats_5seed_vs_classic")),
    "F3": ("classic\\_unified $-$ classic (unification on classic substrate)", bq(f"{M}/floorleg_classic_unified_pooled")),
}

lines = []
lines.append("% Auto-generated by scripts/build_manuscript_tables.py — do not hand-edit; re-run to refresh.")
lines.append("% Sources: exp/ablation_matrix/stats/final_5seed_*, exp/fast_iter/smooth_qd_*/stats_5seed_vs_classic,")
lines.append("%          exp/ablation_matrix/stats/floorleg_classic_unified_pooled.")
lines.append("")
lines.append("\\begin{table}[t]")
lines.append("\\centering")
lines.append("\\caption{Best-quality contrasts on the 13-problem hard subset (RTLLM + VerilogEval), "
             "5 seeds, problems-as-clusters bootstrap. Negative $=$ first arm worse. "
             "Parity rule: CI entirely above $-0.03$.}")
lines.append("\\label{tab:main-results}")
lines.append("\\begin{tabular}{lccc}")
lines.append("\\toprule")
lines.append("Contrast & Mean $\\Delta$ & 95\\% CI & sign-$p$ \\\\")
lines.append("\\midrule")
for key in ("F1", "F2", "F23v2", "F23v1", "F3"):
    label, d = rows[key]
    lines.append(f"{label} & {fmt(d)} \\\\")
lines.append("\\bottomrule")
lines.append("\\end{tabular}")
lines.append("\\end{table}")
lines.append("")

# Harder-benchmark capability table (RealBench valid counts + CVDP)
rb = {}
gmc = Path(f"{S}/capability_remap/grade_mismatch_compare.json")
gv2 = Path(f"{S}/capability_remap/grade_mismatch_v2.json")
if gmc.is_file():
    d = json.loads(gmc.read_text())
    rb["classic"] = sum(v.get("valid", 0) for v in d.get("classic", {}).values())
    rb["qd_target"] = sum(v.get("valid", 0) for v in d.get("qd", {}).values())
if gv2.is_file():
    d = json.loads(gv2.read_text())
    rb["qd_v2"] = sum(v.get("valid", 0) for v in d.get("qd_v2", {}).values())

lines.append("\\begin{table}[t]")
lines.append("\\centering")
lines.append("\\caption{Capability at harder/newer-benchmark scale. Functionally-valid candidates. "
             "RealBench: 7 dependency-complete e203 modules (valids only on the 2 smallest; "
             "0 on all 5 larger for every arm). CVDP: 9 cocotb design tasks. No method beats "
             "classic; the binding limit is LLM spec-comprehension, not search.}")
lines.append("\\label{tab:capability}")
lines.append("\\begin{tabular}{lcc}")
lines.append("\\toprule")
lines.append("Arm & RealBench valid (/7) & CVDP valid (/9) \\\\")
lines.append("\\midrule")
lines.append(f"classic & {rb.get('classic','--')} & 0 \\\\")
lines.append(f"qd\\_target (radical QD) & {rb.get('qd_target','--')} & 0 \\\\")
lines.append(f"smooth-QD V2 (\\emph{{our method}}) & {rb.get('qd_v2','--')} & 0 \\\\")
lines.append("\\bottomrule")
lines.append("\\end{tabular}")
lines.append("\\end{table}")
lines.append("")

OUT.write_text("\n".join(lines))
print(f"wrote {OUT}")
print("\n=== preview ===")
print("\n".join(lines))
