#!/usr/bin/env python3
"""Generate a classic-vs-variant pair launcher from a locked subset config.

Launcher scripts were previously edited with sed, which silently produced
a hybrid problem list (the 2026-06-13 incident). This generator reads the
problem list straight from the locked subset YAML and emits a launcher
that runs the classic arm, the variant arm, the paired statistics, and
the rerun-ledger entries.

The variant arm's extra flags come from ``--variant-flags`` verbatim; the
QD primary target's frozen flags live in the v3 launcher and doc 07 and
can be pasted from there. ``--api-backend openrouter`` switches both arms
to the API fallback (GPU handoff rule).
"""

from __future__ import annotations

import argparse
import shlex
from pathlib import Path

import yaml

TEMPLATE = """#!/usr/bin/env bash
# Generated by scripts/generate_pair_launcher.py - do not hand-edit.
set -uo pipefail
cd /workspace
source .venv/bin/activate
set -a; source .env; set +a

TAG={tag}
ROOT="exp/fast_iter/${{TAG}}"
mkdir -p "${{ROOT}}"

COMMON=(--benchmarks {benchmarks}
        --problems {problems}
        --model_name {model} --api_backend {api_backend}{vllm_flags}
        --population_size {population} --num_generations {generations} --seed {seed}
        --max_tokens 128000 --diff_max_tokens 128000
        --total_worker_slots {slots} --max_active_problems {active} --max_workers_per_problem {per_problem})

echo "=== classic arm start: $(date -u +%H:%M:%S) ==="
python scripts/run_backend.py --backend revolution "${{COMMON[@]}}" \\
  --save_path "${{ROOT}}/classic" > "${{ROOT}}/classic_launch.log" 2>&1
echo "=== classic arm done rc=$?: $(date -u +%H:%M:%S) ==="

echo "=== variant arm start: $(date -u +%H:%M:%S) ==="
python scripts/run_backend.py --backend revolution "${{COMMON[@]}}" \\
  {variant_flags} \\
  --save_path "${{ROOT}}/variant" > "${{ROOT}}/variant_launch.log" 2>&1
echo "=== variant arm done rc=$?: $(date -u +%H:%M:%S) ==="

python scripts/report_journal_statistics.py \\
  --pair "{seed}=${{ROOT}}/classic/revolution=${{ROOT}}/variant/revolution" \\
  --output-dir "${{ROOT}}/stats" --gate-profile none \\
  > "${{ROOT}}/stats_launch.log" 2>&1 || echo "stats rc=$?"

python scripts/journal_rerun_ledger.py append \\
  --purpose {purpose}_classic --run-root "${{ROOT}}/classic" --seeds {seed} \\
  --note "generated pair launcher: classic arm"
python scripts/journal_rerun_ledger.py append \\
  --purpose {purpose}_variant --run-root "${{ROOT}}/variant" --seeds {seed} \\
  --note "generated pair launcher: variant arm ({variant_summary})"
echo "=== all done ==="
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--subset-config", type=Path, required=True)
    parser.add_argument("--tag", required=True)
    parser.add_argument("--purpose", required=True)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--api-backend", choices=("vllm", "openrouter"), default="openrouter")
    parser.add_argument("--model", default=None, help="Defaults per backend.")
    parser.add_argument("--population", type=int, default=12)
    parser.add_argument("--generations", type=int, default=3)
    parser.add_argument("--variant-flags", required=True, help="Verbatim extra flags for the variant arm.")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args(argv)

    payload = yaml.safe_load(args.subset_config.read_text(encoding="utf-8"))
    benchmarks = sorted(payload["benchmarks"])
    problems = [
        problem
        for benchmark in benchmarks
        for problem in payload["benchmarks"][benchmark]["problems"]
    ]
    assert problems, "subset config has no problems"
    model = args.model or (
        "openai/gpt-oss-120b" if args.api_backend == "openrouter" else "openai-gpt-oss-120b"
    )
    vllm_flags = (
        "\n        --vllm_host host.docker.internal --vllm_port 8000"
        if args.api_backend == "vllm"
        else ""
    )
    script = TEMPLATE.format(
        tag=shlex.quote(args.tag),
        benchmarks=" ".join(shlex.quote(b) for b in benchmarks),
        problems=" ".join(shlex.quote(p) for p in problems),
        model=shlex.quote(model),
        api_backend=args.api_backend,
        vllm_flags=vllm_flags,
        population=args.population,
        generations=args.generations,
        seed=args.seed,
        slots=12,
        active=min(6, len(problems)),
        per_problem=4,
        variant_flags=args.variant_flags,
        purpose=args.purpose,
        variant_summary=args.variant_flags[:80],
    )
    args.output.write_text(script, encoding="utf-8")
    args.output.chmod(0o755)
    print(f"Launcher -> {args.output} ({len(problems)} problems, {args.api_backend})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
