#!/usr/bin/env python3
"""Generate the predeclared 5-arm component-attribution ablation launcher.

Narrative (frozen): hard subset, debug budget, seeds 1001-1003; arms are
classic, classic+unified operator, full QD with the six-operator suite,
QD with scalar elites, and the full QD target. Stats are pairwise
classic-vs-arm per seed through the same journal_stats machinery as the
main gates; every arm also ships the budget-parity artifact. The classic
arm runs once per seed and is shared by all four contrasts.
"""

from __future__ import annotations

import argparse
import shlex
from pathlib import Path

import yaml

QD_TARGET_FLAGS = (
    "--search_mode revolution_qd --qd_archive_type grid_quantile "
    "--qd_descriptor_profile journal_logic_ff_width_3d "
    "--qd_grid_quantile_warmup_successes 8 --qd_cell_mode pareto_front "
    "--qd_max_elites_per_cell 5 --qd_objectives ppa "
    "--qd_two_parent_probability 0.5 "
    "--qd_operator_kind single_thought_operator "
    "--qd_operator_one_parent_fraction 0.5 "
    "--qd_operator_archive_context_size 4 "
    "--qd_operator_two_parent_allow_intra_bin "
    "--qd_rebinning_kind ks_triggered --qd_rebinning_recent_generations 3 "
    "--qd_rebinning_min_archive_members 20 "
    "--qd_rebinning_cooldown_generations 3 "
    "--qd_rebinning_base_p_threshold 0.05 "
    "--representation_kind thought_only --code_samples_per_thought 4"
)

ARMS: dict[str, str] = {
    "classic_unified": "--classic_operator_kind single_thought_operator",
    "qd_six_operators": QD_TARGET_FLAGS.replace(
        "--qd_operator_kind single_thought_operator", "--qd_operator_kind eoh_strategies"
    ),
    "qd_scalar_elites": QD_TARGET_FLAGS.replace(
        "--qd_cell_mode pareto_front", "--qd_cell_mode scalar_elite"
    ).replace(" --qd_max_elites_per_cell 5", ""),
    "qd_target": QD_TARGET_FLAGS,
}

HEADER = """#!/usr/bin/env bash
# Generated by scripts/generate_ablation_matrix.py - do not hand-edit.
set -uo pipefail
cd /workspace
source .venv/bin/activate
set -a; source .env; set +a
export PYTHONUNBUFFERED=1

ROOT="exp/ablation_matrix"
mkdir -p "${ROOT}"
"""

RUN_BLOCK = """
echo "=== {label} start: $(date -u +%H:%M:%S) ==="
python scripts/run_backend.py --backend revolution \\
  --benchmarks {benchmarks} \\
  --problems {problems} \\
  --model_name {model} --api_backend openrouter \\
  --population_size {population} --num_generations {generations} --seed {seed} \\
  --max_tokens 32768 --diff_max_tokens 32768 \\
  --total_worker_slots 12 --max_active_problems 6 --max_workers_per_problem 4 \\
  {extra_flags} \\
  --save_path "${{ROOT}}/{arm}/seed_{seed}" \\
  > "${{ROOT}}/{arm}_seed{seed}_launch.log" 2>&1
echo "=== {label} done rc=$?: $(date -u +%H:%M:%S) ==="
"""

STATS_BLOCK = """
python scripts/report_journal_statistics.py \\
  --pair "{seed}=${{ROOT}}/classic/seed_{seed}/revolution=${{ROOT}}/{arm}/seed_{seed}/revolution" \\
  --output-dir "${{ROOT}}/stats/{arm}_seed{seed}" --gate-profile none \\
  > "${{ROOT}}/stats/{arm}_seed{seed}.log" 2>&1 || echo "stats {arm}/{seed} rc=$?"
python scripts/report_budget_parity.py \\
  --classic-root "${{ROOT}}/classic/seed_{seed}" \\
  --variant-root "${{ROOT}}/{arm}/seed_{seed}" \\
  --output-dir "${{ROOT}}/stats/{arm}_seed{seed}/budget_parity" \\
  > /dev/null 2>&1 || echo "parity {arm}/{seed} rc=$?"
python scripts/journal_rerun_ledger.py append \\
  --purpose ablation_{arm} --run-root "${{ROOT}}/{arm}/seed_{seed}" --seeds {seed} \\
  --note "ablation matrix arm {arm}, seed {seed}"
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--subset-config",
        type=Path,
        default=Path("data/configs/hard_iteration_subset.yaml"),
    )
    parser.add_argument("--seeds", type=int, nargs="+", default=[1001, 1002, 1003])
    parser.add_argument("--population", type=int, default=20)
    parser.add_argument("--generations", type=int, default=5)
    parser.add_argument("--model", default="openai/gpt-oss-120b")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args(argv)

    payload = yaml.safe_load(args.subset_config.read_text(encoding="utf-8"))
    benchmarks = sorted(payload["benchmarks"])
    problems = [
        problem
        for benchmark in benchmarks
        for problem in payload["benchmarks"][benchmark]["problems"]
    ]
    assert problems, "subset config has no problems"

    common = {
        "benchmarks": " ".join(shlex.quote(b) for b in benchmarks),
        "problems": " ".join(shlex.quote(p) for p in problems),
        "model": shlex.quote(args.model),
        "population": args.population,
        "generations": args.generations,
    }
    script = HEADER + 'mkdir -p "${ROOT}/stats"\n'
    for seed in args.seeds:
        script += RUN_BLOCK.format(
            label=f"classic seed {seed}", arm="classic", seed=seed,
            extra_flags="", **common,
        )
        for arm, flags in ARMS.items():
            script += RUN_BLOCK.format(
                label=f"{arm} seed {seed}", arm=arm, seed=seed,
                extra_flags=flags, **common,
            )
            script += STATS_BLOCK.format(arm=arm, seed=seed)
    script += '\necho "=== matrix all done ==="\n'
    args.output.write_text(script, encoding="utf-8")
    args.output.chmod(0o755)
    runs = len(args.seeds) * (1 + len(ARMS))
    print(
        f"Matrix launcher -> {args.output} "
        f"({len(problems)} problems, {runs} runs, {len(ARMS)} contrasts/seed)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
