#!/usr/bin/env python3
"""Package the T44 T11 runtime graph bridge screen."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.package_t40_sparse_warmup_control_matrix import (
    MethodSpec,
    PROBLEMS,
    candidate_rows,
    collect_candidates,
    manifest_rows,
    mark_pooled_fronts,
    plot_count_summary,
    plot_raw_fronts,
    problem_summary_rows,
    write_csv,
    write_viewer,
)

METHODS = (
    MethodSpec(
        "classic_revolution",
        "T44 Classic",
        "t44",
        "classic_revolution/seed_1001/openai_gpt-oss-120b",
        "#1f77b4",
    ),
    MethodSpec(
        "t11_runtime_top8_graph_qd",
        "T44 T11 graph",
        "t44",
        "t11_runtime_top8_graph_qd/seed_1001/openai_gpt-oss-120b",
        "#17becf",
    ),
    MethodSpec(
        "staged_sparse_yield_gate_qd",
        "T43 staged gate",
        "t43",
        "staged_sparse_yield_gate_qd/seed_1001/openai_gpt-oss-120b",
        "#8c564b",
    ),
    MethodSpec(
        "t39_sparse_warmup_elite_slot_qd",
        "T39 one-slot",
        "t39",
        "sparse_warmup_elite_slot_qd/seed_1001/openai_gpt-oss-120b",
        "#2ca02c",
    ),
)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--t44-run-root", required=True, type=Path)
    parser.add_argument("--t43-run-root", required=True, type=Path)
    parser.add_argument("--t39-run-root", required=True, type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    args = parser.parse_args(argv)

    roots = {
        "t44": args.t44_run_root,
        "t43": args.t43_run_root,
        "t39": args.t39_run_root,
    }
    table_dir = args.output_dir / "tables"
    figure_dir = args.output_dir / "figures"
    viewer_dir = args.output_dir / "visualizations" / "direct_ppa_pareto"
    table_dir.mkdir(parents=True, exist_ok=True)
    figure_dir.mkdir(parents=True, exist_ok=True)
    viewer_dir.mkdir(parents=True, exist_ok=True)

    candidates = [
        candidate
        for method in METHODS
        for problem in PROBLEMS
        for candidate in collect_candidates(roots, method, problem)
    ]
    candidates = mark_pooled_fronts(candidates)
    summary_rows = problem_summary_rows(candidates, METHODS)
    write_csv(table_dir / "t44_candidate_ppa_points.csv", candidate_rows(candidates))
    write_csv(table_dir / "t44_problem_method_summary.csv", summary_rows)
    write_csv(table_dir / "t44_method_manifest.csv", manifest_rows(roots, METHODS))
    plot_raw_fronts(
        candidates,
        figure_dir / "t44_raw_area_power_fronts.png",
        METHODS,
        "T44 T11 Runtime Graph Bridge",
    )
    plot_count_summary(
        summary_rows,
        figure_dir / "t44_front_count_summary.png",
        METHODS,
        "T44 T11 Runtime Graph Bridge",
    )
    write_viewer(
        viewer_dir / "index.html",
        summary_rows,
        title="T44 Direct PPA Fronts",
        image_name="t44_raw_area_power_fronts.png",
    )
    (viewer_dir / "metrics.json").write_text(
        json.dumps(summary_rows, indent=2) + "\n",
        encoding="utf-8",
    )
    (viewer_dir / "README.md").write_text(
        "# T44 Direct PPA Pareto Viewer\n\n"
        "This is the reader-facing raw area-power supplement generated by\n"
        "`scripts/package_t44_t11_runtime_graph_bridge.py`.\n\n"
        "- `index.html`: filesystem-openable direct PPA-front view.\n"
        "- `metrics.json`: problem/method summary used by the HTML table.\n"
        "- `screenshot.png`: add after Playwright or manual visual inspection.\n\n"
        "This supplement is not the full Phase 03.1 linked archive/PPA viewer.\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
