/* Generated by Yosys 0.54+29 (git sha1 67583fee4, g++ 9.5.0 -fPIC -O3) */

module TopModule(clk, slowena, reset, q);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  input clk;
  wire clk;
  output [3:0] q;
  wire [3:0] q;
  input reset;
  wire reset;
  input slowena;
  wire slowena;
  INV_X1 _27_ (
    .A(q[0]),
    .ZN(_07_)
  );
  INV_X1 _28_ (
    .A(q[1]),
    .ZN(_08_)
  );
  NOR2_X1 _29_ (
    .A1(_07_),
    .A2(_08_),
    .ZN(_00_)
  );
  BUF_X2 _30_ (
    .A(slowena),
    .Z(_09_)
  );
  XNOR2_X1 _31_ (
    .A(q[0]),
    .B(_09_),
    .ZN(_10_)
  );
  NOR2_X1 _32_ (
    .A1(reset),
    .A2(_10_),
    .ZN(_03_)
  );
  INV_X1 _33_ (
    .A(reset),
    .ZN(_11_)
  );
  NAND2_X1 _34_ (
    .A1(q[0]),
    .A2(_09_),
    .ZN(_12_)
  );
  NAND3_X1 _35_ (
    .A1(q[1]),
    .A2(_11_),
    .A3(_12_),
    .ZN(_13_)
  );
  INV_X2 _36_ (
    .A(q[3]),
    .ZN(_14_)
  );
  OAI211_X1 _37_ (
    .A(_08_),
    .B(_11_),
    .C1(_14_),
    .C2(q[2]),
    .ZN(_15_)
  );
  OAI21_X1 _38_ (
    .A(_13_),
    .B1(_15_),
    .B2(_12_),
    .ZN(_04_)
  );
  INV_X1 _39_ (
    .A(_09_),
    .ZN(_16_)
  );
  NAND3_X1 _40_ (
    .A1(q[2]),
    .A2(_16_),
    .A3(_11_),
    .ZN(_17_)
  );
  NAND3_X1 _41_ (
    .A1(_02_),
    .A2(_09_),
    .A3(_11_),
    .ZN(_18_)
  );
  NOR4_X4 _42_ (
    .A1(_07_),
    .A2(q[1]),
    .A3(q[2]),
    .A4(_14_),
    .ZN(_19_)
  );
  OAI21_X1 _43_ (
    .A(_17_),
    .B1(_18_),
    .B2(_19_),
    .ZN(_05_)
  );
  NAND3_X1 _44_ (
    .A1(q[3]),
    .A2(_16_),
    .A3(_11_),
    .ZN(_20_)
  );
  NAND4_X1 _45_ (
    .A1(_14_),
    .A2(_01_),
    .A3(_09_),
    .A4(_11_),
    .ZN(_21_)
  );
  OR3_X2 _46_ (
    .A1(_14_),
    .A2(_01_),
    .A3(reset),
    .ZN(_22_)
  );
  OAI211_X2 _47_ (
    .A(_20_),
    .B(_21_),
    .C1(_19_),
    .C2(_22_),
    .ZN(_06_)
  );
  HA_X1 _48_ (
    .A(q[2]),
    .B(_00_),
    .CO(_01_),
    .S(_02_)
  );
  DFF_X1 _49_ (
    .CK(clk),
    .D(_03_),
    .Q(q[0]),
    .QN(_26_)
  );
  DFF_X1 _50_ (
    .CK(clk),
    .D(_04_),
    .Q(q[1]),
    .QN(_25_)
  );
  DFF_X1 _51_ (
    .CK(clk),
    .D(_05_),
    .Q(q[2]),
    .QN(_24_)
  );
  DFF_X1 _52_ (
    .CK(clk),
    .D(_06_),
    .Q(q[3]),
    .QN(_23_)
  );
endmodule
