/* Generated by Yosys 0.54+29 (git sha1 67583fee4, g++ 9.5.0 -fPIC -O3) */

module TopModule(clk, in, reset, out_bytes, done);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire \byte_buffer[0] ;
  wire \byte_buffer[10] ;
  wire \byte_buffer[11] ;
  wire \byte_buffer[12] ;
  wire \byte_buffer[13] ;
  wire \byte_buffer[14] ;
  wire \byte_buffer[15] ;
  wire \byte_buffer[1] ;
  wire \byte_buffer[2] ;
  wire \byte_buffer[3] ;
  wire \byte_buffer[4] ;
  wire \byte_buffer[5] ;
  wire \byte_buffer[6] ;
  wire \byte_buffer[7] ;
  wire \byte_buffer[8] ;
  wire \byte_buffer[9] ;
  input clk;
  wire clk;
  output done;
  wire done;
  input [7:0] in;
  wire [7:0] in;
  output [23:0] out_bytes;
  wire [23:0] out_bytes;
  input reset;
  wire reset;
  wire \state[0] ;
  wire \state[1] ;
  wire \state[2] ;
  INV_X1 _129_ (
    .A(\state[1] ),
    .ZN(_082_)
  );
  BUF_X2 _130_ (
    .A(reset),
    .Z(_083_)
  );
  INV_X1 _131_ (
    .A(_083_),
    .ZN(_084_)
  );
  BUF_X2 _132_ (
    .A(_084_),
    .Z(_044_)
  );
  BUF_X4 _133_ (
    .A(\state[0] ),
    .Z(_045_)
  );
  INV_X1 _134_ (
    .A(_045_),
    .ZN(_046_)
  );
  BUF_X2 _135_ (
    .A(in[3]),
    .Z(_047_)
  );
  OAI211_X1 _136_ (
    .A(_082_),
    .B(_044_),
    .C1(_046_),
    .C2(_047_),
    .ZN(_002_)
  );
  INV_X1 _137_ (
    .A(_047_),
    .ZN(_048_)
  );
  NOR3_X1 _138_ (
    .A1(_048_),
    .A2(_046_),
    .A3(_083_),
    .ZN(_001_)
  );
  INV_X1 _139_ (
    .A(\state[2] ),
    .ZN(_049_)
  );
  NOR2_X1 _140_ (
    .A1(_049_),
    .A2(_083_),
    .ZN(_000_)
  );
  NOR2_X4 _141_ (
    .A1(_082_),
    .A2(_083_),
    .ZN(_050_)
  );
  BUF_X4 _142_ (
    .A(_050_),
    .Z(_003_)
  );
  MUX2_X1 _143_ (
    .A(out_bytes[0]),
    .B(in[0]),
    .S(_003_),
    .Z(_004_)
  );
  MUX2_X1 _144_ (
    .A(out_bytes[1]),
    .B(in[1]),
    .S(_003_),
    .Z(_005_)
  );
  MUX2_X1 _145_ (
    .A(out_bytes[2]),
    .B(in[2]),
    .S(_003_),
    .Z(_006_)
  );
  MUX2_X1 _146_ (
    .A(out_bytes[3]),
    .B(_047_),
    .S(_003_),
    .Z(_007_)
  );
  MUX2_X1 _147_ (
    .A(out_bytes[4]),
    .B(in[4]),
    .S(_003_),
    .Z(_008_)
  );
  MUX2_X1 _148_ (
    .A(out_bytes[5]),
    .B(in[5]),
    .S(_003_),
    .Z(_009_)
  );
  MUX2_X1 _149_ (
    .A(out_bytes[6]),
    .B(in[6]),
    .S(_003_),
    .Z(_010_)
  );
  MUX2_X1 _150_ (
    .A(out_bytes[7]),
    .B(in[7]),
    .S(_003_),
    .Z(_011_)
  );
  MUX2_X1 _151_ (
    .A(out_bytes[8]),
    .B(\byte_buffer[0] ),
    .S(_003_),
    .Z(_012_)
  );
  BUF_X4 _152_ (
    .A(_050_),
    .Z(_051_)
  );
  MUX2_X1 _153_ (
    .A(out_bytes[9]),
    .B(\byte_buffer[1] ),
    .S(_051_),
    .Z(_013_)
  );
  MUX2_X1 _154_ (
    .A(out_bytes[10]),
    .B(\byte_buffer[2] ),
    .S(_051_),
    .Z(_014_)
  );
  MUX2_X1 _155_ (
    .A(out_bytes[11]),
    .B(\byte_buffer[3] ),
    .S(_051_),
    .Z(_015_)
  );
  MUX2_X1 _156_ (
    .A(out_bytes[12]),
    .B(\byte_buffer[4] ),
    .S(_051_),
    .Z(_016_)
  );
  MUX2_X1 _157_ (
    .A(out_bytes[13]),
    .B(\byte_buffer[5] ),
    .S(_051_),
    .Z(_017_)
  );
  MUX2_X1 _158_ (
    .A(out_bytes[14]),
    .B(\byte_buffer[6] ),
    .S(_051_),
    .Z(_018_)
  );
  MUX2_X1 _159_ (
    .A(out_bytes[15]),
    .B(\byte_buffer[7] ),
    .S(_051_),
    .Z(_019_)
  );
  MUX2_X1 _160_ (
    .A(out_bytes[16]),
    .B(\byte_buffer[8] ),
    .S(_051_),
    .Z(_020_)
  );
  MUX2_X1 _161_ (
    .A(out_bytes[17]),
    .B(\byte_buffer[9] ),
    .S(_051_),
    .Z(_021_)
  );
  MUX2_X1 _162_ (
    .A(out_bytes[18]),
    .B(\byte_buffer[10] ),
    .S(_051_),
    .Z(_022_)
  );
  MUX2_X1 _163_ (
    .A(out_bytes[19]),
    .B(\byte_buffer[11] ),
    .S(_050_),
    .Z(_023_)
  );
  MUX2_X1 _164_ (
    .A(out_bytes[20]),
    .B(\byte_buffer[12] ),
    .S(_050_),
    .Z(_024_)
  );
  MUX2_X1 _165_ (
    .A(out_bytes[21]),
    .B(\byte_buffer[13] ),
    .S(_050_),
    .Z(_025_)
  );
  MUX2_X1 _166_ (
    .A(out_bytes[22]),
    .B(\byte_buffer[14] ),
    .S(_050_),
    .Z(_026_)
  );
  MUX2_X1 _167_ (
    .A(out_bytes[23]),
    .B(\byte_buffer[15] ),
    .S(_050_),
    .Z(_027_)
  );
  BUF_X2 _168_ (
    .A(_084_),
    .Z(_052_)
  );
  AND2_X1 _169_ (
    .A1(_052_),
    .A2(\byte_buffer[0] ),
    .ZN(_053_)
  );
  AND2_X1 _170_ (
    .A1(_044_),
    .A2(in[0]),
    .ZN(_054_)
  );
  NOR3_X2 _171_ (
    .A1(\state[2] ),
    .A2(\state[1] ),
    .A3(_045_),
    .ZN(_055_)
  );
  AOI21_X4 _172_ (
    .A(_055_),
    .B1(_045_),
    .B2(_048_),
    .ZN(_056_)
  );
  MUX2_X1 _173_ (
    .A(_053_),
    .B(_054_),
    .S(_056_),
    .Z(_028_)
  );
  AND2_X1 _174_ (
    .A1(_052_),
    .A2(\byte_buffer[1] ),
    .ZN(_057_)
  );
  AND2_X1 _175_ (
    .A1(_044_),
    .A2(in[1]),
    .ZN(_058_)
  );
  MUX2_X1 _176_ (
    .A(_057_),
    .B(_058_),
    .S(_056_),
    .Z(_029_)
  );
  AND2_X1 _177_ (
    .A1(_052_),
    .A2(\byte_buffer[2] ),
    .ZN(_059_)
  );
  AND2_X1 _178_ (
    .A1(_044_),
    .A2(in[2]),
    .ZN(_060_)
  );
  MUX2_X1 _179_ (
    .A(_059_),
    .B(_060_),
    .S(_056_),
    .Z(_030_)
  );
  AOI211_X1 _180_ (
    .A(_047_),
    .B(_045_),
    .C1(_049_),
    .C2(_082_),
    .ZN(_061_)
  );
  OR3_X4 _181_ (
    .A1(\state[2] ),
    .A2(\state[1] ),
    .A3(_045_),
    .ZN(_062_)
  );
  AOI21_X1 _182_ (
    .A(\byte_buffer[3] ),
    .B1(_062_),
    .B2(_047_),
    .ZN(_063_)
  );
  NOR3_X1 _183_ (
    .A1(_083_),
    .A2(_061_),
    .A3(_063_),
    .ZN(_031_)
  );
  AND2_X1 _184_ (
    .A1(_084_),
    .A2(\byte_buffer[4] ),
    .ZN(_064_)
  );
  AND2_X1 _185_ (
    .A1(_044_),
    .A2(in[4]),
    .ZN(_065_)
  );
  MUX2_X1 _186_ (
    .A(_064_),
    .B(_065_),
    .S(_056_),
    .Z(_032_)
  );
  AND2_X1 _187_ (
    .A1(_084_),
    .A2(\byte_buffer[5] ),
    .ZN(_066_)
  );
  AND2_X1 _188_ (
    .A1(_044_),
    .A2(in[5]),
    .ZN(_067_)
  );
  MUX2_X1 _189_ (
    .A(_066_),
    .B(_067_),
    .S(_056_),
    .Z(_033_)
  );
  AND2_X1 _190_ (
    .A1(_084_),
    .A2(\byte_buffer[6] ),
    .ZN(_068_)
  );
  AND2_X1 _191_ (
    .A1(_044_),
    .A2(in[6]),
    .ZN(_069_)
  );
  MUX2_X1 _192_ (
    .A(_068_),
    .B(_069_),
    .S(_056_),
    .Z(_034_)
  );
  AND2_X1 _193_ (
    .A1(_084_),
    .A2(\byte_buffer[7] ),
    .ZN(_070_)
  );
  AND2_X1 _194_ (
    .A1(_044_),
    .A2(in[7]),
    .ZN(_071_)
  );
  MUX2_X1 _195_ (
    .A(_070_),
    .B(_071_),
    .S(_056_),
    .Z(_035_)
  );
  AND2_X1 _196_ (
    .A1(_044_),
    .A2(\byte_buffer[8] ),
    .ZN(_072_)
  );
  OAI21_X4 _197_ (
    .A(_062_),
    .B1(_046_),
    .B2(_047_),
    .ZN(_073_)
  );
  MUX2_X1 _198_ (
    .A(_053_),
    .B(_072_),
    .S(_073_),
    .Z(_036_)
  );
  AND2_X1 _199_ (
    .A1(_044_),
    .A2(\byte_buffer[9] ),
    .ZN(_074_)
  );
  MUX2_X1 _200_ (
    .A(_057_),
    .B(_074_),
    .S(_073_),
    .Z(_037_)
  );
  AND2_X1 _201_ (
    .A1(_052_),
    .A2(\byte_buffer[10] ),
    .ZN(_075_)
  );
  MUX2_X1 _202_ (
    .A(_059_),
    .B(_075_),
    .S(_073_),
    .Z(_038_)
  );
  AND2_X1 _203_ (
    .A1(_052_),
    .A2(\byte_buffer[11] ),
    .ZN(_076_)
  );
  AND2_X1 _204_ (
    .A1(_052_),
    .A2(\byte_buffer[3] ),
    .ZN(_077_)
  );
  MUX2_X1 _205_ (
    .A(_076_),
    .B(_077_),
    .S(_056_),
    .Z(_039_)
  );
  AND2_X1 _206_ (
    .A1(_052_),
    .A2(\byte_buffer[12] ),
    .ZN(_078_)
  );
  MUX2_X1 _207_ (
    .A(_064_),
    .B(_078_),
    .S(_073_),
    .Z(_040_)
  );
  AND2_X1 _208_ (
    .A1(_052_),
    .A2(\byte_buffer[13] ),
    .ZN(_079_)
  );
  MUX2_X1 _209_ (
    .A(_066_),
    .B(_079_),
    .S(_073_),
    .Z(_041_)
  );
  AND2_X1 _210_ (
    .A1(_052_),
    .A2(\byte_buffer[14] ),
    .ZN(_080_)
  );
  MUX2_X1 _211_ (
    .A(_068_),
    .B(_080_),
    .S(_073_),
    .Z(_042_)
  );
  AND2_X1 _212_ (
    .A1(_052_),
    .A2(\byte_buffer[15] ),
    .ZN(_081_)
  );
  MUX2_X1 _213_ (
    .A(_070_),
    .B(_081_),
    .S(_073_),
    .Z(_043_)
  );
  DFF_X1 _214_ (
    .CK(clk),
    .D(_002_),
    .Q(\state[0] ),
    .QN(_127_)
  );
  DFF_X1 _215_ (
    .CK(clk),
    .D(_000_),
    .Q(\state[1] ),
    .QN(_128_)
  );
  DFF_X1 _216_ (
    .CK(clk),
    .D(_001_),
    .Q(\state[2] ),
    .QN(_126_)
  );
  DFF_X1 _217_ (
    .CK(clk),
    .D(_003_),
    .Q(done),
    .QN(_125_)
  );
  DFF_X1 _218_ (
    .CK(clk),
    .D(_004_),
    .Q(out_bytes[0]),
    .QN(_124_)
  );
  DFF_X1 _219_ (
    .CK(clk),
    .D(_005_),
    .Q(out_bytes[1]),
    .QN(_123_)
  );
  DFF_X1 _220_ (
    .CK(clk),
    .D(_006_),
    .Q(out_bytes[2]),
    .QN(_122_)
  );
  DFF_X1 _221_ (
    .CK(clk),
    .D(_007_),
    .Q(out_bytes[3]),
    .QN(_121_)
  );
  DFF_X1 _222_ (
    .CK(clk),
    .D(_008_),
    .Q(out_bytes[4]),
    .QN(_120_)
  );
  DFF_X1 _223_ (
    .CK(clk),
    .D(_009_),
    .Q(out_bytes[5]),
    .QN(_119_)
  );
  DFF_X1 _224_ (
    .CK(clk),
    .D(_010_),
    .Q(out_bytes[6]),
    .QN(_118_)
  );
  DFF_X1 _225_ (
    .CK(clk),
    .D(_011_),
    .Q(out_bytes[7]),
    .QN(_117_)
  );
  DFF_X1 _226_ (
    .CK(clk),
    .D(_012_),
    .Q(out_bytes[8]),
    .QN(_116_)
  );
  DFF_X1 _227_ (
    .CK(clk),
    .D(_013_),
    .Q(out_bytes[9]),
    .QN(_115_)
  );
  DFF_X1 _228_ (
    .CK(clk),
    .D(_014_),
    .Q(out_bytes[10]),
    .QN(_114_)
  );
  DFF_X1 _229_ (
    .CK(clk),
    .D(_015_),
    .Q(out_bytes[11]),
    .QN(_113_)
  );
  DFF_X1 _230_ (
    .CK(clk),
    .D(_016_),
    .Q(out_bytes[12]),
    .QN(_112_)
  );
  DFF_X1 _231_ (
    .CK(clk),
    .D(_017_),
    .Q(out_bytes[13]),
    .QN(_111_)
  );
  DFF_X1 _232_ (
    .CK(clk),
    .D(_018_),
    .Q(out_bytes[14]),
    .QN(_110_)
  );
  DFF_X1 _233_ (
    .CK(clk),
    .D(_019_),
    .Q(out_bytes[15]),
    .QN(_109_)
  );
  DFF_X1 _234_ (
    .CK(clk),
    .D(_020_),
    .Q(out_bytes[16]),
    .QN(_108_)
  );
  DFF_X1 _235_ (
    .CK(clk),
    .D(_021_),
    .Q(out_bytes[17]),
    .QN(_107_)
  );
  DFF_X1 _236_ (
    .CK(clk),
    .D(_022_),
    .Q(out_bytes[18]),
    .QN(_106_)
  );
  DFF_X1 _237_ (
    .CK(clk),
    .D(_023_),
    .Q(out_bytes[19]),
    .QN(_105_)
  );
  DFF_X1 _238_ (
    .CK(clk),
    .D(_024_),
    .Q(out_bytes[20]),
    .QN(_104_)
  );
  DFF_X1 _239_ (
    .CK(clk),
    .D(_025_),
    .Q(out_bytes[21]),
    .QN(_103_)
  );
  DFF_X1 _240_ (
    .CK(clk),
    .D(_026_),
    .Q(out_bytes[22]),
    .QN(_102_)
  );
  DFF_X1 _241_ (
    .CK(clk),
    .D(_027_),
    .Q(out_bytes[23]),
    .QN(_101_)
  );
  DFF_X1 _242_ (
    .CK(clk),
    .D(_028_),
    .Q(\byte_buffer[0] ),
    .QN(_100_)
  );
  DFF_X1 _243_ (
    .CK(clk),
    .D(_029_),
    .Q(\byte_buffer[1] ),
    .QN(_099_)
  );
  DFF_X1 _244_ (
    .CK(clk),
    .D(_030_),
    .Q(\byte_buffer[2] ),
    .QN(_098_)
  );
  DFF_X1 _245_ (
    .CK(clk),
    .D(_031_),
    .Q(\byte_buffer[3] ),
    .QN(_097_)
  );
  DFF_X1 _246_ (
    .CK(clk),
    .D(_032_),
    .Q(\byte_buffer[4] ),
    .QN(_096_)
  );
  DFF_X1 _247_ (
    .CK(clk),
    .D(_033_),
    .Q(\byte_buffer[5] ),
    .QN(_095_)
  );
  DFF_X1 _248_ (
    .CK(clk),
    .D(_034_),
    .Q(\byte_buffer[6] ),
    .QN(_094_)
  );
  DFF_X1 _249_ (
    .CK(clk),
    .D(_035_),
    .Q(\byte_buffer[7] ),
    .QN(_093_)
  );
  DFF_X1 _250_ (
    .CK(clk),
    .D(_036_),
    .Q(\byte_buffer[8] ),
    .QN(_092_)
  );
  DFF_X1 _251_ (
    .CK(clk),
    .D(_037_),
    .Q(\byte_buffer[9] ),
    .QN(_091_)
  );
  DFF_X1 _252_ (
    .CK(clk),
    .D(_038_),
    .Q(\byte_buffer[10] ),
    .QN(_090_)
  );
  DFF_X1 _253_ (
    .CK(clk),
    .D(_039_),
    .Q(\byte_buffer[11] ),
    .QN(_089_)
  );
  DFF_X1 _254_ (
    .CK(clk),
    .D(_040_),
    .Q(\byte_buffer[12] ),
    .QN(_088_)
  );
  DFF_X1 _255_ (
    .CK(clk),
    .D(_041_),
    .Q(\byte_buffer[13] ),
    .QN(_087_)
  );
  DFF_X1 _256_ (
    .CK(clk),
    .D(_042_),
    .Q(\byte_buffer[14] ),
    .QN(_086_)
  );
  DFF_X1 _257_ (
    .CK(clk),
    .D(_043_),
    .Q(\byte_buffer[15] ),
    .QN(_085_)
  );
endmodule
